import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/Theme/theme-provider";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import SessionWrapper from "@/lib/SessionWrapper";
import App from "./App";

export const metadata: Metadata = {
  title: "Car Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-100 dark:bg-zinc-900">
      <SessionWrapper>
        <App>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        </App>
      </SessionWrapper>
      
      <ToastContainer
      position="top-left"
      autoClose={5000}
      hideProgressBar={false}
      newestOnTop
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
      style={{
        width: 'auto',
        maxWidth: '350px', 
        margin: '5px',
        fontSize: '12px',
        fontWeight: 'bold'
      }}
      toastStyle={{
        backgroundColor: '#868686',
        color: '#fff',
        borderRadius: '22px',
        padding: '10px 15px',
        boxShadow: '0 3px 10px rgba(0, 0, 0, 0.1)',
        margin: '0 auto',
        width: 'fit-content',
        minWidth: '200px',  
        maxWidth: '300px'  
      }}
    />
      </body>
    </html>
  );
}
